// Pre-generated static map from text to offline audio assets
export const audioMap = {
  "Welcome to Angles Around a Point! Let's master full turns, straight lines, and opposite angle twins!": "/assets/audio/audio_welcome_home_0.mp3",
  "John is building a paper pinwheel. It has four blades meeting at the centre point.": "/assets/audio/audio_wonder_hook_0.mp3",
  "He measures three of the angles: ninety, eighty, and seventy degrees. What is the fourth angle?": "/assets/audio/audio_wonder_hook_1.mp3",
  "Let's discover the secret number that all angles around a point share!": "/assets/audio/audio_wonder_hook_2.mp3",
  "Can you discover the secret angle that closes the pinwheel around the center?": "/assets/audio/audio_wonder_prompt_0.mp3",
  "Not quite! Add 90 + 80 + 70 = 240. What number makes 240 + ? = 360?": "/assets/audio/audio_wonder_retry_0.mp3",
  "Brilliant! Ninety plus eighty plus seventy plus one hundred and twenty equals three hundred and sixty degrees! All angles around a point always total three hundred and sixty degrees!": "/assets/audio/audio_wonder_success_0.mp3",
  "Sarah cuts a round pizza into slices that all meet at the centre point.": "/assets/audio/audio_story_panel1_0.mp3",
  "Notice how all the angle points touch at one single spot in the middle!": "/assets/audio/audio_story_panel1_1.mp3",
  "No matter how many slices Sarah cuts, if you go all the way around the central point, you complete one full rotation.": "/assets/audio/audio_story_panel2_0.mp3",
  "One full turn is ALWAYS three hundred and sixty degrees!": "/assets/audio/audio_story_panel2_1.mp3",
  "If Sarah knows three slice angles are ninety, one hundred, and ninety-five degrees, she can subtract their sum from three hundred and sixty degrees!": "/assets/audio/audio_story_panel3_0.mp3",
  "Ninety plus one hundred plus ninety-five equals two hundred and eighty-five. So the missing slice must be seventy-five degrees!": "/assets/audio/audio_story_panel3_1.mp3",
  "Mike is watching traffic at a T-junction. A straight road forms a half turn across a flat line point.": "/assets/audio/audio_story_panel4_0.mp3",
  "A straight line is a half turn — it always adds up to one hundred and eighty degrees!": "/assets/audio/audio_story_panel4_1.mp3",
  "When two straight lines cross each other, the angles opposite each other across the vertex point are identical twins!": "/assets/audio/audio_story_panel5_0.mp3",
  "Vertically opposite angles are ALWAYS EQUAL!": "/assets/audio/audio_story_panel5_1.mp3",
  "Now you have the three key secrets: Point = 360 degrees, Straight Line = 180 degrees, Opposite = Equal.": "/assets/audio/audio_story_panel6_0.mp3",
  "Let's test these superpowers in the interactive simulation stations!": "/assets/audio/audio_story_panel6_1.mp3",
  "Drag the wedges around the point until the circle closes at three hundred and sixty degrees.": "/assets/audio/audio_station_a_instruction_0.mp3",
  "Awesome! You built a complete three hundred and sixty degree circle turn!": "/assets/audio/audio_station_a_success_0.mp3",
  "Drag the arm until the two angles balance to one hundred and eighty degrees.": "/assets/audio/audio_station_b_instruction_0.mp3",
  "Perfect balance! Angles on a straight line always sum to one hundred and eighty degrees!": "/assets/audio/audio_station_b_success_0.mp3",
  "Tap the two angles that are directly opposite each other across the crossing point.": "/assets/audio/audio_station_c_instruction_0.mp3",
  "Spot on! Vertically opposite angle twins are always equal!": "/assets/audio/audio_station_c_success_0.mp3",
  "Yes! That's exactly right — you found the missing angle!": "/assets/audio/audio_correct_0.mp3",
  "What a journey today! Can you draw a point with three angles and explain why they add up to three hundred and sixty degrees?": "/assets/audio/audio_reflect_prompt_0.mp3",
  "Great reflection! You explained how angles meeting at a point form one full rotation of three hundred and sixty degrees.": "/assets/audio/audio_reflect_success_0.mp3",
  "Lesson complete! You are a Three Sixty Degree Champion!": "/assets/audio/audio_lesson_complete_0.mp3"
};
